### ISSUE TITLE
Upstream CI tests failing because of incompatability between `pre-commit>=3.6` and Python 3.8

### ISSUE THREAD

**Issue by jonded94** [nijel/utidylib#106]
Since this commit (https://github.com/nijel/utidylib/commit/84a5fc4ebd8b45fc4805ba737f75ea89bf428a93) the CI tests are failing.

This is because `pre-commit` dropped support for Python 3.8 in `pre-commit` version 3.6.0. 

Why is `pre-commit` always being updated by `dependabot`? Since this dependency is a dev/lint dependency only, it does not make sense to me dropping support for Python 3.8 of `utidylib` but instead lock `pre-commit` to 3.5.0 for example.

**Comment by nijel** [comment]
I didn't notice the test breakage in https://github.com/nijel/utidylib/pull/99 and merged that change.

Fixed via https://github.com/nijel/utidylib/pull/108
