### ISSUE TITLE
Usable for checking HTML?

### ISSUE THREAD

**Issue by guettli** [nijel/utidylib#4]
I am looking for html5-valiator for Python.

Can utidylib be used for checking (not cleaning) HTML?

Related question at softrecs: [html validator](https://softwarerecs.stackexchange.com/questions/77388/html-validator-library-or-command-line-tool)

**Comment by nijel** [comment]
I don't think it's good use. Tidy is designed to cleanup and format the markup. You can compare whether tidy output matches input and treat this as check result, but I think there must be better tools to validate the markup.

**Comment by guettli** [comment]
Thank you for your fast response. Nevertheless, I use it for this purpose now. `doc.errrors` provide a good hint on what's wrong.

I published my code here: https://github.com/guettli/django-check-html-middleware

If you know a better library to lint html, then please speak up. Thank you

**Comment by guettli** [comment]
Just for the records. I found this library, which is maybe better suite to my use-case: https://github.com/svenkreiss/html5validator
