### ISSUE TITLE
Please download from this page (pip version is currently outdated).

### ISSUE THREAD

**Issue by guettli** [nijel/utidylib#5]
on: https://cihar.com/software/utidylib/

> Installation
> 
> Please download from this page (pip version is currently outdated).

Please update the version at pypi.

The current package at pypi uses `six` but, does not specify a dependency to it.

I guess `six` is not needed any more.

A new package at pypi would be very nice.

BTW, I created a small check-html middleware for django, which uses your lib:

https://github.com/guettli/django-check-html-middleware

**Comment by nijel** [comment]
> Please update the version at pypi.

It's already done, the website is outdated now :-).

**Comment by nijel** [comment]
I've just released Python 3 only version with dropped six dependency - https://pypi.org/project/uTidylib/
